# CMake generated Testfile for 
# Source directory: /home/ygballou/net-a45
# Build directory: /home/ygballou/net-a45/built
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_pkouakou_dummy "./game_test_pkouakou" "dummy")
set_tests_properties(test_pkouakou_dummy PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;60;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_set_piece_orientation "./game_test_pkouakou" "game_set_piece_orientation")
set_tests_properties(test_pkouakou_game_set_piece_orientation PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;61;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_new_empty "./game_test_pkouakou" "game_new_empty")
set_tests_properties(test_pkouakou_game_new_empty PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;62;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_equal "./game_test_pkouakou" "game_equal")
set_tests_properties(test_pkouakou_game_equal PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;63;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_play_move "./game_test_pkouakou" "game_play_move")
set_tests_properties(test_pkouakou_game_play_move PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;64;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_default_solution "./game_test_pkouakou" "game_default_solution")
set_tests_properties(test_pkouakou_game_default_solution PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;65;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_check_edge "./game_test_pkouakou" "game_check_edge")
set_tests_properties(test_pkouakou_game_check_edge PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;66;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_shuffle_orientation "./game_test_pkouakou" "game_shuffle_orientation")
set_tests_properties(test_pkouakou_game_shuffle_orientation PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;67;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_new_empty_ext "./game_test_pkouakou" "game_new_empty_ext")
set_tests_properties(test_pkouakou_game_new_empty_ext PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;68;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_undo "./game_test_pkouakou" "game_undo")
set_tests_properties(test_pkouakou_game_undo PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;69;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_load "./game_test_pkouakou" "game_load")
set_tests_properties(test_pkouakou_game_load PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;70;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_solve "./game_test_pkouakou" "game_solve")
set_tests_properties(test_pkouakou_game_solve PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;71;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_pkouakou_game_nb_solutions "./game_test_pkouakou" "game_nb_solutions")
set_tests_properties(test_pkouakou_game_nb_solutions PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;72;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_print "./game_test_ygballou" "game_print")
set_tests_properties(test_ygballou_game_print PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;74;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_dummy "./game_test_ygballou" "dummy")
set_tests_properties(test_ygballou_dummy PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;75;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_new "./game_test_ygballou" "game_new")
set_tests_properties(test_ygballou_game_new PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;76;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_won "./game_test_ygballou" "game_won")
set_tests_properties(test_ygballou_game_won PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;77;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_get_ajacent_square "./game_test_ygballou" "game_get_ajacent_square")
set_tests_properties(test_ygballou_game_get_ajacent_square PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;78;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_is_well_paired "./game_test_ygballou" "game_is_well_paired")
set_tests_properties(test_ygballou_game_is_well_paired PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;79;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_delete "./game_test_ygballou" "game_delete")
set_tests_properties(test_ygballou_game_delete PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;80;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_get_piece_shape "./game_test_ygballou" "game_get_piece_shape")
set_tests_properties(test_ygballou_game_get_piece_shape PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;81;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_nb_rows "./game_test_ygballou" "game_nb_rows")
set_tests_properties(test_ygballou_game_nb_rows PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;82;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_nb_cols "./game_test_ygballou" "game_nb_cols")
set_tests_properties(test_ygballou_game_nb_cols PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;83;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_is_wrapping "./game_test_ygballou" "game_is_wrapping")
set_tests_properties(test_ygballou_game_is_wrapping PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;84;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_save "./game_test_ygballou" "game_save")
set_tests_properties(test_ygballou_game_save PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;85;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ygballou_game_random "./game_test_ygballou" "game_random")
set_tests_properties(test_ygballou_game_random PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;86;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_dummy "./game_test_ambakounzous" "dummy")
set_tests_properties(test_ambakounzous_dummy PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;88;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_copy "./game_test_ambakounzous" "game_copy")
set_tests_properties(test_ambakounzous_game_copy PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;89;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_get_piece_orientation "./game_test_ambakounzous" "game_get_piece_orientation")
set_tests_properties(test_ambakounzous_game_get_piece_orientation PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;90;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_reset_orientation "./game_test_ambakounzous" "game_reset_orientation")
set_tests_properties(test_ambakounzous_game_reset_orientation PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;91;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_set_piece_shape "./game_test_ambakounzous" "game_set_piece_shape")
set_tests_properties(test_ambakounzous_game_set_piece_shape PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;92;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_default "./game_test_ambakounzous" "game_default")
set_tests_properties(test_ambakounzous_game_default PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;93;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_has_half_edge "./game_test_ambakounzous" "game_has_half_edge")
set_tests_properties(test_ambakounzous_game_has_half_edge PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;94;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_is_connected "./game_test_ambakounzous" "game_is_connected")
set_tests_properties(test_ambakounzous_game_is_connected PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;95;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_new_ext "./game_test_ambakounzous" "game_new_ext")
set_tests_properties(test_ambakounzous_game_new_ext PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;96;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
add_test(test_ambakounzous_game_redo "./game_test_ambakounzous" "game_redo")
set_tests_properties(test_ambakounzous_game_redo PROPERTIES  _BACKTRACE_TRIPLES "/home/ygballou/net-a45/CMakeLists.txt;97;add_test;/home/ygballou/net-a45/CMakeLists.txt;0;")
